apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: emotion-api

resources:
  - ../../base
  - namespace.yaml

images:
  - name: emotion-api
    newName: 619759452242.dkr.ecr.us-east-2.amazonaws.com/emotion-api
    newTag: v0.3.1
