apiVersion: v1
kind: Service
metadata:
  name: emotion-api
  labels:
    app.kubernetes.io/name: emotion-api
    app.kubernetes.io/component: inference
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: emotion-api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
